settings:
  title: 'Best Box Hosting'
  url: 'https://status.bestboxhosting.com' # used for Slack messages
  logo: transparent.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: bbh-website
    name: Website
    url: 'https://bestboxhosting.com/'
    method: GET
    expectStatus: 200

  - id: bbh-billing
    name: Billing
    url: 'https://billing.bestboxhosting.com/'
    method: GET
    expectStatus: 301 # Temporary, ?todo: remove when billing is released.

  - id: bbh-panel
    name: Panel
    url: 'https://panel.bestboxhosting.com/'
    method: GET
    expectStatus: 200
